name: searxiv-scraper-container

on:
  workflow_call:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.github_token }}

      - name: Build container
        run: docker buildx build -t ghcr.io/${{ github.repository }}:${{ github.run_number }}
          -t ghcr.io/${{ github.repository }}:latest
          --cache-from type=gha,scope=$GITHUB_REF_NAME-image
          --cache-to type=gha,mode=max,scope=$GITHUB_REF_NAME-image .

      - name: Push container
        run: docker push -a ghcr.io/${{ github.repository }}

