name: searxiv-scraper

on:
  push:
    branches: ["*"]

permissions:
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  container:
    uses: ./.github/workflows/container.yml
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
